/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package admveterinaria.Interface;


import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrador
 */


  /**
     * Creates new form HomeMedicoVeterinario
     */
public class HomeEncargadoBodega extends javax.swing.JFrame {
    
   

    DefaultTableModel dtmDatosListarRecetas = new DefaultTableModel();


    public HomeEncargadoBodega() {

        this.dtmDatosListarRecetas = new DefaultTableModel();
        this.dtmDatosListarRecetas.addColumn("Rut");
        this.dtmDatosListarRecetas.addColumn("Nombre Apellidos");
        this.dtmDatosListarRecetas.addColumn("Medicamentos");
        this.dtmDatosListarRecetas.addColumn("Dosis Medicamentos");
        this.dtmDatosListarRecetas.addColumn("Transcripción");
        
        initComponents();
    } 
    
    
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jColorChooser1 = new javax.swing.JColorChooser();
        jSeparator1 = new javax.swing.JSeparator();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jIntAdministrarProductos = new javax.swing.JInternalFrame();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jTextField23 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jTextField24 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel41 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jTextField25 = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jTextField26 = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        jTextField32 = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jLabel56 = new javax.swing.JLabel();
        jIntListarEliminarProducto = new javax.swing.JInternalFrame();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jTextField33 = new javax.swing.JTextField();
        jButton21 = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton22 = new javax.swing.JButton();
        jSeparator10 = new javax.swing.JSeparator();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jIntIngresarVenta = new javax.swing.JInternalFrame();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jTextField34 = new javax.swing.JTextField();
        jTextField35 = new javax.swing.JTextField();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jTextField36 = new javax.swing.JTextField();
        jTextField37 = new javax.swing.JTextField();
        jLabel68 = new javax.swing.JLabel();
        jTextField38 = new javax.swing.JTextField();
        jLabel69 = new javax.swing.JLabel();
        jTextField39 = new javax.swing.JTextField();
        jTextField40 = new javax.swing.JTextField();
        jButton25 = new javax.swing.JButton();
        jLabel62 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        jSeparator15 = new javax.swing.JSeparator();
        jTextField41 = new javax.swing.JTextField();
        jButton26 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenu4.setText("File");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        jMenuItem6.setText("jMenuItem6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administración \"ENCARGADO BODEGA\"");
        setMinimumSize(new java.awt.Dimension(970, 500));
        setSize(new java.awt.Dimension(0, 0));

        jDesktopPane1.setBackground(new java.awt.Color(204, 204, 204));
        jDesktopPane1.setEnabled(false);
        jDesktopPane1.setLocation(new java.awt.Point(0, 20));
        jDesktopPane1.setMinimumSize(new java.awt.Dimension(700, 700));

        jIntAdministrarProductos.setClosable(true);
        jIntAdministrarProductos.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jIntAdministrarProductos.setIconifiable(true);
        jIntAdministrarProductos.setMaximizable(true);
        jIntAdministrarProductos.setTitle("Administración Productos Veterinaria ");
        jIntAdministrarProductos.setVisible(false);

        jLabel34.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 102, 102));
        jLabel34.setText("INGRESAR PRODUCTO");

        jLabel35.setText("Codigo Barra");

        jLabel37.setText("Nombre Producto");

        jLabel39.setText("Tipo ");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Medicamentos", "Insumos Simples" }));

        jLabel41.setText("Codigo Interno Veterinaria");

        jButton12.setText("Buscar");

        jLabel43.setText("Precio");

        jLabel44.setText("STOCK");

        jLabel55.setForeground(new java.awt.Color(0, 153, 153));
        jLabel55.setText("La Busqueda podra ser efectiva ingresando cualquiera de los dos Códigos. ");

        jButton18.setText("Ingresar");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jButton19.setText("Cancelar");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        jButton20.setText("Registrar Nuevo Producto");

        jLabel56.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(0, 102, 102));
        jLabel56.setText("REGISTRAR NUEVO PRODUCTO");

        org.jdesktop.layout.GroupLayout jIntAdministrarProductosLayout = new org.jdesktop.layout.GroupLayout(jIntAdministrarProductos.getContentPane());
        jIntAdministrarProductos.getContentPane().setLayout(jIntAdministrarProductosLayout);
        jIntAdministrarProductosLayout.setHorizontalGroup(
            jIntAdministrarProductosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jIntAdministrarProductosLayout.createSequentialGroup()
                .add(jIntAdministrarProductosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jIntAdministrarProductosLayout.createSequentialGroup()
                        .add(139, 139, 139)
                        .add(jIntAdministrarProductosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jTextField23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 156, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jIntAdministrarProductosLayout.createSequentialGroup()
                                .add(38, 38, 38)
                                .add(jLabel35)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jIntAdministrarProductosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jIntAdministrarProductosLayout.createSequentialGroup()
                                .add(jTextField25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 128, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(18, 18, 18))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel41)))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jIntAdministrarProductosLayout.createSequentialGroup()
                        .addContainerGap(150, Short.MAX_VALUE)
                        .add(jLabel56)
                        .add(24, 24, 24)))
                .add(115, 115, 115))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jIntAdministrarProductosLayout.createSequentialGroup()
                .add(0, 0, Short.MAX_VALUE)
                .add(jLabel55, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 505, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(101, 101, 101))
            .add(jIntAdministrarProductosLayout.createSequentialGroup()
                .add(32, 32, 32)
                .add(jButton19)
                .add(37, 37, 37)
                .add(jIntAdministrarProductosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jIntAdministrarProductosLayout.createSequentialGroup()
                        .add(jLabel37)
                        .add(18, 18, 18)
                        .add(jLabel45)
                        .add(86, 86, 86)
                        .add(jTextField24, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 136, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jIntAdministrarProductosLayout.createSequentialGroup()
                        .add(jIntAdministrarProductosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel39)
                            .add(jIntAdministrarProductosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                .add(jLabel44)
                                .add(jLabel43)))
                        .add(172, 172, 172)
                        .add(jIntAdministrarProductosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jComboBox3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 187, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jIntAdministrarProductosLayout.createSequentialGroup()
                                .add(6, 6, 6)
                                .add(jIntAdministrarProductosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jTextField32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jTextField26, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 82, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jIntAdministrarProductosLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jIntAdministrarProductosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jIntAdministrarProductosLayout.createSequentialGroup()
                        .add(jButton12)
                        .add(345, 345, 345))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jIntAdministrarProductosLayout.createSequentialGroup()
                        .add(jButton20)
                        .add(156, 156, 156)
                        .add(jButton18)
                        .add(56, 56, 56))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jIntAdministrarProductosLayout.createSequentialGroup()
                        .add(jLabel34)
                        .add(219, 219, 219))))
        );
        jIntAdministrarProductosLayout.setVerticalGroup(
            jIntAdministrarProductosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jIntAdministrarProductosLayout.createSequentialGroup()
                .add(22, 22, 22)
                .add(jLabel34, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 33, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jLabel56, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 33, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(37, 37, 37)
                .add(jIntAdministrarProductosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jIntAdministrarProductosLayout.createSequentialGroup()
                        .add(jLabel35)
                        .add(18, 18, 18)
                        .add(jTextField23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jIntAdministrarProductosLayout.createSequentialGroup()
                        .add(jLabel41)
                        .add(18, 18, 18)
                        .add(jTextField25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 30, Short.MAX_VALUE)
                .add(jButton12, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 39, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jLabel55)
                .add(15, 15, 15)
                .add(jIntAdministrarProductosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jTextField24, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel37)
                    .add(jLabel45))
                .add(jIntAdministrarProductosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jIntAdministrarProductosLayout.createSequentialGroup()
                        .add(32, 32, 32)
                        .add(jLabel39))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jIntAdministrarProductosLayout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jComboBox3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(24, 24, 24)
                .add(jIntAdministrarProductosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel43)
                    .add(jTextField26, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(22, 22, 22)
                .add(jIntAdministrarProductosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jTextField32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel44))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 62, Short.MAX_VALUE)
                .add(jIntAdministrarProductosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton19, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButton20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButton18, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(34, 34, 34))
        );

        jIntAdministrarProductos.setBounds(210, 0, 850, 680);
        jDesktopPane1.add(jIntAdministrarProductos, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jIntListarEliminarProducto.setClosable(true);
        jIntListarEliminarProducto.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jIntListarEliminarProducto.setIconifiable(true);
        jIntListarEliminarProducto.setMaximizable(true);
        jIntListarEliminarProducto.setTitle("Listado Productos ");
        jIntListarEliminarProducto.setVisible(false);

        jLabel57.setFont(new java.awt.Font("Apple Braille", 1, 36)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(0, 102, 102));
        jLabel57.setText("LISTAR - ELIMINAR PRODUCTOS  ");

        jLabel58.setText("Codigo Barra");

        jTextField33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField33ActionPerformed(evt);
            }
        });

        jButton21.setText("Buscar");

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Seleccionar", "Codigo Barra", "Codigo Interno", "Nombre Producto", "Tipo", "Precio", "Stock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane8.setViewportView(jTable3);

        jButton22.setText("Listar Productos");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });

        jButton23.setText("Eliminar");

        jButton24.setText("Cancelar");
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jIntListarEliminarProductoLayout = new org.jdesktop.layout.GroupLayout(jIntListarEliminarProducto.getContentPane());
        jIntListarEliminarProducto.getContentPane().setLayout(jIntListarEliminarProductoLayout);
        jIntListarEliminarProductoLayout.setHorizontalGroup(
            jIntListarEliminarProductoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jIntListarEliminarProductoLayout.createSequentialGroup()
                .add(401, 401, 401)
                .add(jIntListarEliminarProductoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jTextField33, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 142, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jIntListarEliminarProductoLayout.createSequentialGroup()
                        .add(29, 29, 29)
                        .add(jButton21)))
                .add(0, 0, Short.MAX_VALUE))
            .add(jIntListarEliminarProductoLayout.createSequentialGroup()
                .add(jIntListarEliminarProductoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jIntListarEliminarProductoLayout.createSequentialGroup()
                        .add(69, 69, 69)
                        .add(jIntListarEliminarProductoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jSeparator10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 824, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jIntListarEliminarProductoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(jButton22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 157, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(jScrollPane8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 833, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                    .add(jIntListarEliminarProductoLayout.createSequentialGroup()
                        .add(431, 431, 431)
                        .add(jLabel58)))
                .addContainerGap(74, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jIntListarEliminarProductoLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jLabel57)
                .add(194, 194, 194))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jIntListarEliminarProductoLayout.createSequentialGroup()
                .add(97, 97, 97)
                .add(jButton24)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jButton23)
                .add(207, 207, 207))
        );
        jIntListarEliminarProductoLayout.setVerticalGroup(
            jIntListarEliminarProductoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jIntListarEliminarProductoLayout.createSequentialGroup()
                .add(31, 31, 31)
                .add(jLabel57)
                .add(17, 17, 17)
                .add(jSeparator10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jLabel58)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jTextField33, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton21)
                .add(12, 12, 12)
                .add(jButton22)
                .add(27, 27, 27)
                .add(jScrollPane8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 285, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jIntListarEliminarProductoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton23)
                    .add(jButton24))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jIntListarEliminarProducto.setBounds(100, 10, 1000, 670);
        jDesktopPane1.add(jIntListarEliminarProducto, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jIntIngresarVenta.setClosable(true);
        jIntIngresarVenta.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jIntIngresarVenta.setIconifiable(true);
        jIntIngresarVenta.setMaximizable(true);
        jIntIngresarVenta.setVisible(false);

        jLabel59.setFont(new java.awt.Font("Apple Braille", 0, 24)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(0, 102, 102));
        jLabel59.setText("GENERAR VENTA ");

        jLabel60.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(0, 102, 102));
        jLabel60.setText("Atención Mascota");

        jLabel61.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(0, 102, 102));
        jLabel61.setText("Productos  Solicitados");

        jLabel63.setText("Precio");

        jLabel64.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel64.setText("Total");

        jLabel65.setText("Nombre");

        jTextField34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField34ActionPerformed(evt);
            }
        });

        jLabel66.setText("Codigo Barra ");

        jLabel67.setText("Nombre Producto");

        jLabel68.setText("Cantidad");

        jTextField38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField38ActionPerformed(evt);
            }
        });

        jLabel69.setText("Precio");

        jTextField40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField40ActionPerformed(evt);
            }
        });

        jButton25.setText("Agregar");
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });

        jLabel62.setText("Codigo Atención");

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo ", "Nombre ", "Cantidad", "Precio", "Sub-Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane9.setViewportView(jTable4);

        jButton26.setText("Generar Boleta");
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jIntIngresarVentaLayout = new org.jdesktop.layout.GroupLayout(jIntIngresarVenta.getContentPane());
        jIntIngresarVenta.getContentPane().setLayout(jIntIngresarVentaLayout);
        jIntIngresarVentaLayout.setHorizontalGroup(
            jIntIngresarVentaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jIntIngresarVentaLayout.createSequentialGroup()
                .add(52, 52, 52)
                .add(jIntIngresarVentaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jIntIngresarVentaLayout.createSequentialGroup()
                        .add(jScrollPane9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 782, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(0, 0, Short.MAX_VALUE))
                    .add(jIntIngresarVentaLayout.createSequentialGroup()
                        .add(jIntIngresarVentaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jIntIngresarVentaLayout.createSequentialGroup()
                                .add(110, 110, 110)
                                .add(jLabel62))
                            .add(jIntIngresarVentaLayout.createSequentialGroup()
                                .add(jLabel65)
                                .add(21, 21, 21)
                                .add(jTextField36, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 125, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jIntIngresarVentaLayout.createSequentialGroup()
                                .add(jLabel68)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(jTextField38, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 51, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jIntIngresarVentaLayout.createSequentialGroup()
                                .add(jLabel63)
                                .add(33, 33, 33)
                                .add(jIntIngresarVentaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jTextField34, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 183, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jTextField35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 77, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 299, Short.MAX_VALUE)
                        .add(jIntIngresarVentaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jIntIngresarVentaLayout.createSequentialGroup()
                                .add(jLabel61)
                                .add(160, 160, 160))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jIntIngresarVentaLayout.createSequentialGroup()
                                .add(jIntIngresarVentaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel66)
                                    .add(jTextField39, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 129, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jTextField37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 76, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .add(178, 178, 178))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jIntIngresarVentaLayout.createSequentialGroup()
                                .add(jTextField40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 190, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(166, 166, 166))))))
            .add(jIntIngresarVentaLayout.createSequentialGroup()
                .add(136, 136, 136)
                .add(jLabel60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 204, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, Short.MAX_VALUE))
            .add(jIntIngresarVentaLayout.createSequentialGroup()
                .add(jIntIngresarVentaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jIntIngresarVentaLayout.createSequentialGroup()
                        .add(359, 359, 359)
                        .add(jButton25))
                    .add(jIntIngresarVentaLayout.createSequentialGroup()
                        .add(313, 313, 313)
                        .add(jLabel59))
                    .add(jIntIngresarVentaLayout.createSequentialGroup()
                        .add(111, 111, 111)
                        .add(jSeparator15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 617, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jIntIngresarVentaLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .add(jIntIngresarVentaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jIntIngresarVentaLayout.createSequentialGroup()
                        .add(jIntIngresarVentaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jIntIngresarVentaLayout.createSequentialGroup()
                                .add(jLabel64)
                                .add(18, 18, 18))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jIntIngresarVentaLayout.createSequentialGroup()
                                .add(jButton26)
                                .add(190, 190, 190)))
                        .add(jTextField41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 139, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(58, 58, 58))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jIntIngresarVentaLayout.createSequentialGroup()
                        .add(jSeparator13, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 356, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jIntIngresarVentaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jIntIngresarVentaLayout.createSequentialGroup()
                                .add(37, 37, 37)
                                .add(jSeparator14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 356, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jIntIngresarVentaLayout.createSequentialGroup()
                                .add(26, 26, 26)
                                .add(jIntIngresarVentaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel69)
                                    .add(jLabel67))))
                        .add(80, 80, 80))))
        );
        jIntIngresarVentaLayout.setVerticalGroup(
            jIntIngresarVentaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jIntIngresarVentaLayout.createSequentialGroup()
                .add(33, 33, 33)
                .add(jLabel59)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jSeparator15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(37, 37, 37)
                .add(jIntIngresarVentaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jIntIngresarVentaLayout.createSequentialGroup()
                        .add(jLabel60)
                        .add(11, 11, 11)
                        .add(jSeparator13, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(3, 3, 3))
                    .add(jIntIngresarVentaLayout.createSequentialGroup()
                        .add(jLabel61)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jSeparator14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(1, 1, 1)))
                .add(jIntIngresarVentaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel62, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel66))
                .add(6, 6, 6)
                .add(jIntIngresarVentaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jTextField34, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextField40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(30, 30, 30)
                .add(jIntIngresarVentaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jTextField35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel63)
                    .add(jLabel67)
                    .add(jTextField39, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(14, 14, 14)
                .add(jIntIngresarVentaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jIntIngresarVentaLayout.createSequentialGroup()
                        .add(0, 0, Short.MAX_VALUE)
                        .add(jIntIngresarVentaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel65)
                            .add(jTextField36, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(18, 18, 18)
                        .add(jIntIngresarVentaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jTextField38, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel68, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(48, 48, 48))
                    .add(jIntIngresarVentaLayout.createSequentialGroup()
                        .add(jIntIngresarVentaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jTextField37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel69))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jButton25)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jScrollPane9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 126, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(jIntIngresarVentaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jIntIngresarVentaLayout.createSequentialGroup()
                        .add(18, 18, 18)
                        .add(jIntIngresarVentaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jTextField41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel64)))
                    .add(jIntIngresarVentaLayout.createSequentialGroup()
                        .add(50, 50, 50)
                        .add(jButton26, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(56, 56, 56))
        );

        jIntIngresarVenta.setBounds(70, 0, 890, 700);
        jDesktopPane1.add(jIntIngresarVenta, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jMenu7.setText("                  Productos                           ");

        jMenuItem10.setText("Administración de Productos ");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem10);

        jMenuItem12.setText("Generar Listado de los Productos");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem12);

        jMenuBar1.add(jMenu7);

        jMenu8.setText("        Administracion de las Ventas         ");

        jMenuItem8.setText("Productos + Atención Mascota");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem8);

        jMenuBar1.add(jMenu8);

        setJMenuBar(jMenuBar1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .add(jDesktopPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 1225, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(59, 59, 59)
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 951, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(205, 205, 205)
                        .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(0, 0, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jDesktopPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling c ode here:
        this.jIntAdministrarProductos.setVisible(true);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
        this.jIntAdministrarProductos.setVisible(false);
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jTextField33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField33ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
        this.jIntListarEliminarProducto.setVisible(true);
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        // TODO add your handling code here:
        this.jIntListarEliminarProducto.setVisible(false);
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jTextField34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField34ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField34ActionPerformed

    private void jTextField38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField38ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField38ActionPerformed

    private void jTextField40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField40ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField40ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        this.jIntIngresarVenta.setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    //public 
    
         public void init () {   
        
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeMedicoVeterinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeMedicoVeterinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeMedicoVeterinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeMedicoVeterinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new HomeEncargadoBodega().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JInternalFrame jIntAdministrarProductos;
    private javax.swing.JInternalFrame jIntIngresarVenta;
    private javax.swing.JInternalFrame jIntListarEliminarProducto;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField32;
    private javax.swing.JTextField jTextField33;
    private javax.swing.JTextField jTextField34;
    private javax.swing.JTextField jTextField35;
    private javax.swing.JTextField jTextField36;
    private javax.swing.JTextField jTextField37;
    private javax.swing.JTextField jTextField38;
    private javax.swing.JTextField jTextField39;
    private javax.swing.JTextField jTextField40;
    private javax.swing.JTextField jTextField41;
    // End of variables declaration//GEN-END:variables
}
