/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

import admveterinaria.Interface.HomeEncargadoBodega;
import admveterinaria.Interface.HomeMedicoVeterinario;
import admveterinaria.Interface.HomeRecepcionista;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import validacion.Control;

/**
 *
 * @author Administrador
 */
public class login extends javax.swing.JFrame {

    static String usuario=null;
    static String clave=null;
    static int cont=0;
    Control control;
    
    public login()
    {
        
        initComponents();
        usuario="medico";
        clave="medicoVeterinario";
        control=new Control();
        
    }
    
     
    /**
     * Creates new form login
     */


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane = new javax.swing.JOptionPane();
        Login = new javax.swing.JPanel();
        btnSalirSistema = new javax.swing.JButton();
        jBtnIngresoUsuario = new javax.swing.JButton();
        jTxtUsuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPswClave = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOGIN");
        setUndecorated(true);

        btnSalirSistema.setText("Salir");
        btnSalirSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirSistemaActionPerformed(evt);
            }
        });

        jBtnIngresoUsuario.setText("Ingresar");
        jBtnIngresoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIngresoUsuarioActionPerformed(evt);
            }
        });

        jTxtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtUsuarioActionPerformed(evt);
            }
        });

        jLabel3.setText("Clave");

        jLabel2.setText("Usuario");

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Clínica Veterinaria ");

        jPswClave.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPswClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPswClaveActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout LoginLayout = new org.jdesktop.layout.GroupLayout(Login);
        Login.setLayout(LoginLayout);
        LoginLayout.setHorizontalGroup(
            LoginLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(LoginLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(LoginLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, LoginLayout.createSequentialGroup()
                        .add(jLabel2)
                        .add(106, 106, 106))
                    .add(LoginLayout.createSequentialGroup()
                        .add(jLabel3)
                        .add(83, 83, 83)))
                .add(LoginLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jTxtUsuario)
                    .add(jPswClave, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE))
                .add(157, 157, 157))
            .add(LoginLayout.createSequentialGroup()
                .add(31, 31, 31)
                .add(LoginLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(LoginLayout.createSequentialGroup()
                        .add(btnSalirSistema, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 114, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jBtnIngresoUsuario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 120, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jSeparator1))
                .add(48, 48, 48))
            .add(LoginLayout.createSequentialGroup()
                .add(131, 131, 131)
                .add(jLabel1)
                .addContainerGap(164, Short.MAX_VALUE))
        );
        LoginLayout.setVerticalGroup(
            LoginLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(LoginLayout.createSequentialGroup()
                .add(11, 11, 11)
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 57, Short.MAX_VALUE)
                .add(LoginLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jTxtUsuario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel2))
                .add(36, 36, 36)
                .add(LoginLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(jPswClave, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(51, 51, 51)
                .add(LoginLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btnSalirSistema, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jBtnIngresoUsuario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(29, 29, 29))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(Login, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .add(Login, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirSistemaActionPerformed
        // TODO add your handling code here:
        
        System.exit(0);
    }//GEN-LAST:event_btnSalirSistemaActionPerformed

    private void jBtnIngresoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIngresoUsuarioActionPerformed
        try {
        
            String usuario= this.jTxtUsuario.getText();
            HomeMedicoVeterinario perfilMedico=new HomeMedicoVeterinario();
            HomeRecepcionista perfilRecepcionista=new HomeRecepcionista();
            HomeEncargadoBodega perfilEncargadoBodega=new HomeEncargadoBodega();
            
            if(control.verificarUsuario(this.jTxtUsuario.getText(), this.jPswClave.getText()))
            {
                if(usuario.equals("medico") )
                {
                    perfilMedico.init();
                }
                else if(usuario.equals("recepcionista"))
                {
                    perfilRecepcionista.init();
                }else if(usuario.equals("bodega"))
                {
                    perfilEncargadoBodega.init();
                }
                
            }else{
           
          cont++;
          if (cont==3)
          { JOptionPane.showMessageDialog(null,"MAXIMO DE INTENTOS PERMITIDOS, SE CIERRA LA APLICACIÓN ",
                  "AVISO DE SISTEMA", JOptionPane.PLAIN_MESSAGE);
            System.exit(0);
          }
          else
          { JOptionPane.showMessageDialog(null,"VERIFIQUE CREDENCIALES :"+cont+" intentos fallidos",
                  "AVISO DE SISTEMA", JOptionPane.PLAIN_MESSAGE);
          }
          
         }   
        }
                        
         catch (Exception ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
                  
    }//GEN-LAST:event_jBtnIngresoUsuarioActionPerformed
    
 
    private void jPswClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPswClaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPswClaveActionPerformed

private void jTxtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtUsuarioActionPerformed
 // TODO add your handling code here:
}//GEN-LAST:event_jTxtUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new login().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Login;
    private javax.swing.JButton btnSalirSistema;
    private javax.swing.JButton jBtnIngresoUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JOptionPane jOptionPane;
    private javax.swing.JPasswordField jPswClave;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTxtUsuario;
    // End of variables declaration//GEN-END:variables
 
 
}

